services:
  nanomq:
    image: emqx/nanomq:latest
    environment:
      NANOMQ_CONF_PATH: /etc/nanomq/nanomq.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1883:1883"
    volumes:
      - ./nanomq.conf:/etc/nanomq/nanomq.conf
      - ./nanomq_acl.conf:/etc/nanomq/nanomq_acl.conf

  bridge:
    build: .
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MQTT_BROKER: tcp://nanomq:1883
      REDIS_URL: redis://host.docker.internal:6379/1
    depends_on:
      nanomq:
        condition: service_started
