mqtt {
    allow_anonymous = false
}

auth {
    http_auth {
        enable = true

        auth_req {
            url = "http://host.docker.internal:8000/mqtt/auth"
            method = "POST"
            headers.content-type = "application/x-www-form-urlencoded"
            params = {username = "%u", password = "%P"}
        }
    }
}

acl = {include "/etc/nanomq/nanomq_acl.conf"}
